merge_protections:
  - name: Force ticket association
    description: Make sure PR has a ticket associated
    if:
      - base = main
    success_conditions:
      - body ~= Fixes
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
